openapi: 3.0.3
info:
  title: 'Internal HTTP API'
  version: '0.0.0'
paths:
  "/api/requestresponse":
    get:
      summary: "Get a list of request-response pair"
      description: >
        This endpoint returns a list of request-response pairs that were generated in response to the request about the open-api to mock.
      responses:
        '200':
          $ref: "#/components/responses/200RequestResponseListResponse"
        '500':
          $ref: "#/components/responses/500ProblemDetailResponse"

components:

  schemas:
    ProblemDetail:
      # https://www.rfc-editor.org/rfc/rfc7807#section-3.1
      type: object
      properties:
        type:
          type: string
          format: uri
          description: >
            A URI reference [RFC3986] that identifies the
            problem type.  This specification encourages that, when
            dereferenced, it provide human-readable documentation for the
            problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
            this member is not present, its value is assumed to be
            "about:blank".
          default: about:blank
          example: about:blank
        title:
          type: string
          description: >
            A short, human-readable summary of the problem
            type.  It SHOULD NOT change from occurrence to occurrence of the
            problem, except for purposes of localization (e.g., using
            proactive content negotiation; see [RFC7231], Section 3.4).
        status:
          type: integer
          format: int32
          description: >
            The HTTP status code ([RFC7231], Section 6)
            generated by the origin server for this occurrence of the problem.
          minimum: 100
          maximum: 599
          example: 200
        detail:
          type: string
          description: >
            A human-readable explanation specific to this
            occurrence of the problem.
          example: The given request is invalid.
        instance:
          type: string
          format: uri
          description: >
            A URI reference that identifies the specific
            occurrence of the problem.  It may or may not yield further
            information if dereferenced.
    RequestResponseList:
      type: array
      items:
        $ref: '#/components/schemas/RequestResponse'
    RequestResponse:
      type: object
      properties:
        request:
          $ref: '#/components/schemas/HTTPRequest'
        response:
          $ref: '#/components/schemas/Response'
    HTTPRequest:
      type: object
      properties:
        method:
          type: string
          enum: ["delete", "get", "head", "options", "patch", "post", "put", "trace"]
        url:
          type: string
          format: uri
        headers:
          type: object
          additionalProperties:
            type: string
        body:
          type: object
          additionalProperties: true
      required:
        - method
        - url
        - headers
    Response:
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: >
            The HTTP status code ([RFC7231], Section 6)
            generated by the origin server for this occurrence of the problem.
          example: 200
        headers:
          type: object
          additionalProperties:
            type: string
        body:
          type: object
          additionalProperties: true

  responses:
    200RequestResponseListResponse:
      description: List of request-response pair
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/RequestResponseList'
    500ProblemDetailResponse:
      description: The Problem Detail
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/ProblemDetail'
