name: Build container image
description: Build container image and check vulnerabilities

inputs:
  image_tag:
    description: The tag of the image
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

    - name: Build container image
      uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
      with:
        tags: ${{ env.image_tag }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54
      with:
        image-ref: ${{ env.image_tag }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        security-checks: 'vuln,secret,config'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@f6e388ebf0efc915c6c5b165b019ee61a6746a38
      with:
        sarif_file: 'trivy-results.sarif'
