name: Changelog

on:
  push:
    branches:
      - main # Triggered by push on main
    paths:
      - .changeset/** # Only on changes to ./changeset/*

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changelog:
    name: Update CHANGELOG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup Node.js environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: ".node-version"
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            package.json

      - name: Install dependencies
        run: npm ci

      - name: Create next release's PR
        id: changesets
        uses: changesets/action@d89c1de63c7f28ac47ec85ed395f5f1d045d4697
        with:
          # Note: npm install after versioning is necessary to refresh package-lock.json file
          version: npm run version
          commit: "Update CHANGELOG and prepare next release"
          title: "Bump version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
