name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Compile and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate API Schemas
        run: npm run generate:api

      - name: Compile
        run: npm run compile

      - name: Check all dependencies are listed
        run: npm run dependency:check

      - name: Lint code
        run: npm run lint

      - name: Execute tests
        run: npm test

  build-container:
    name: Build container image
    runs-on: ubuntu-latest
    env:
      image_tag: ${{ github.repository }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - uses: ./.github/actions/build-image
        with:
          image_tag: ${{ env.image_tag }}
