name: PR Size labeler

on: pull_request

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@54ef36785e9f4cb5ecf1949cfc9b00dbb621d761
        name: Calculate size and add label to PR
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '50'
          m_label: 'size/m'
          m_max_size: '200'
          l_label: 'size/l'
          l_max_size: '400'
          xl_label: 'size/xl'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 400 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
          files_to_ignore: |
            "package-lock.json"
            "docs/*"
            ".changeset/*"
