name: Push Image

on:
  push:
    tags: '*'

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build-container:
    name: Build container image
    runs-on: ubuntu-latest
    env:
      image_tag: ${{ github.repository }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - uses: ./.github/actions/build-image
        with:
          image_tag: ${{ env.image_tag }}

  deliver:
    name: Build and push container image
    needs: build-container
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Package
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}

      - name: Build and push container image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
